backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://votre-site.netlify.app"
display_url: "https://votre-site.netlify.app"
logo_url: "/images/logo.png"

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - name: "hero"
        label: "Contenu Principal"
        file: "content/hero.md"
        fields:
          - { label: "Titre Principal", name: "title", widget: "string", default: "H&H – International Trading" }
          - { label: "Sous-titre", name: "subtitle", widget: "string", default: "Acting For A Smart Future" }
          - { label: "Texte d'Accueil", name: "welcome_text", widget: "markdown", default: "**Chers partenaires et clients,**\n\nHistoriquement concentrés sur la sous-traitance commerciale, nous sommes fiers d'annoncer notre décision stratégique de nous positionner directement sur le marché chypriote en 2024.\n\nCette transition marque une nouvelle ère pour H&H-IT, nous permettant de renforcer notre compétitivité et de mieux répondre à vos besoins diversifiés." }
          - { label: "Texte du Bouton", name: "button_text", widget: "string", default: "Découvrir nos solutions" }

  - name: "solutions"
    label: "Solutions"
    folder: "content/solutions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Icône", name: "icon", widget: "select", options: [{ label: "Station de recharge", value: "charging-station" }, { label: "Réseau", value: "network-wired" }, { label: "Panneau solaire", value: "solar-panel" }, { label: "Boîte", value: "box" }, { label: "Industrie", value: "industry" }, { label: "Bâtiment", value: "building" }], default: "charging-station" }
      - { label: "Caractéristiques", name: "features", widget: "list", fields: [{ label: "Caractéristique", name: "item", widget: "string" }] }

  - name: "testimonials"
    label: "Témoignages"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Entreprise/Fonction", name: "company", widget: "string" }
      - { label: "Texte du témoignage", name: "text", widget: "text" }