backend:
  name: github
  repo: Djomab/hh-international-trading
  branch: master
  base_url: https://hh-it.netlify.app
  auth_endpoint: /.netlify/identity
  open_authoring: false

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Contenu des différentes pages de votre site"
    files:
      - name: "home"
        label: "Page d’Accueil"
        file: "content/home.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
