backend:
  name: github
  repo: Djomab/hh-international-trading
  branch: master
  # Retire base_url et auth_endpoint - pas nécessaire avec GitHub backend

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  # Hero Section
  - name: "hero"
    label: "Page d'accueil - Hero"
    files:
      - name: "hero"
        label: "Section Hero"
        file: "public/content/hero.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "tagline", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }

  # Solutions
  - name: "solutions"
    label: "Solutions"
    folder: "content/solutions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Icône Font Awesome", name: "icon", widget: "string", hint: "Ex: fa-charging-station" }
      - { label: "Ordre d'affichage", name: "order", widget: "number", default: 1 }
      - { label: "Description", name: "body", widget: "markdown" }