# /admin/config.yml

backend:
  name: github
  repo: Djomab/hh-international-trading   # <-- remplace par ton dépôt GitHub
  branch: master                                    # ou la branche que tu utilises
  base_url: https://hh-it.eu              # requis selon la configuration GitHub via Netlify :contentReference[oaicite:1]{index=1}
  auth_endpoint: callback                              # endpoint d’authentification pour GitHub backend :contentReference[oaicite:2]{index=2}
  site_domain: hh-it.eu/

site_url: https://hh-it.eu                   # <-- remplace par ton domaine personnalisé

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Contenu des différentes pages de votre site"
    files:
      - name: "home"
        label: "Page d’Accueil"
        file: "content/home.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", hint: "Titre principal affiché sur la page d’accueil" }
          - { label: "Sous-titre", name: "subtitle", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown", hint: "Texte principal de la page" }
